from django.core.management.base import BaseCommand
from warden.models import Industry, Company


class Command(BaseCommand):
    help = 'Seed S&P 500 company shells'

    def handle(self, *args, **kwargs):
        # Define industries
        industries = {
            'tech': 'Technology',
            'healthcare': 'Healthcare',
            'financials': 'Financials',
            'consumer-discretionary': 'Consumer Discretionary',
            'consumer-staples': 'Consumer Staples',
            'energy': 'Energy',
            'industrials': 'Industrials',
            'materials': 'Materials',
            'real-estate': 'Real Estate',
            'utilities': 'Utilities',
            'communication': 'Communication Services',
        }

        industry_objs = {}
        for slug, name in industries.items():
            obj, _ = Industry.objects.get_or_create(slug=slug, defaults={'name': name})
            industry_objs[slug] = obj

        # S&P 500 companies (ticker, name, industry_slug)
        companies = [
            ('AAPL', 'Apple', 'tech'),
            ('ABBV', 'AbbVie', 'healthcare'),
            ('ABT', 'Abbott Laboratories', 'healthcare'),
            ('ACN', 'Accenture', 'tech'),
            ('ADBE', 'Adobe', 'tech'),
            ('ADI', 'Analog Devices', 'tech'),
            ('ADM', 'Archer-Daniels-Midland', 'consumer-staples'),
            ('ADP', 'Automatic Data Processing', 'industrials'),
            ('ADSK', 'Autodesk', 'tech'),
            ('AEE', 'Ameren', 'utilities'),
            ('AEP', 'American Electric Power', 'utilities'),
            ('AES', 'AES Corporation', 'utilities'),
            ('AFL', 'Aflac', 'financials'),
            ('AIG', 'American International Group', 'financials'),
            ('AIZ', 'Assurant', 'financials'),
            ('AJG', 'Arthur J. Gallagher', 'financials'),
            ('AKAM', 'Akamai Technologies', 'tech'),
            ('ALB', 'Albemarle', 'materials'),
            ('ALGN', 'Align Technology', 'healthcare'),
            ('ALK', 'Alaska Air Group', 'industrials'),
            ('ALL', 'Allstate', 'financials'),
            ('ALLE', 'Allegion', 'industrials'),
            ('AMAT', 'Applied Materials', 'tech'),
            ('AMCR', 'Amcor', 'materials'),
            ('AMD', 'Advanced Micro Devices', 'tech'),
            ('AME', 'AMETEK', 'industrials'),
            ('AMGN', 'Amgen', 'healthcare'),
            ('AMP', 'Ameriprise Financial', 'financials'),
            ('AMT', 'American Tower', 'real-estate'),
            ('AMZN', 'Amazon', 'consumer-discretionary'),
            ('ANET', 'Arista Networks', 'tech'),
            ('ANSS', 'ANSYS', 'tech'),
            ('AON', 'Aon', 'financials'),
            ('AOS', 'A.O. Smith', 'industrials'),
            ('APA', 'APA Corporation', 'energy'),
            ('APD', 'Air Products', 'materials'),
            ('APH', 'Amphenol', 'tech'),
            ('ARE', 'Alexandria Real Estate', 'real-estate'),
            ('ATO', 'Atmos Energy', 'utilities'),
            ('ATVI', 'Activision Blizzard', 'communication'),
            ('AVB', 'AvalonBay Communities', 'real-estate'),
            ('AVGO', 'Broadcom', 'tech'),
            ('AVY', 'Avery Dennison', 'materials'),
            ('AWK', 'American Water Works', 'utilities'),
            ('AXP', 'American Express', 'financials'),
            ('AZO', 'AutoZone', 'consumer-discretionary'),
            ('BA', 'Boeing', 'industrials'),
            ('BAC', 'Bank of America', 'financials'),
            ('BAX', 'Baxter International', 'healthcare'),
            ('BBWI', 'Bath & Body Works', 'consumer-discretionary'),
            ('BBY', 'Best Buy', 'consumer-discretionary'),
            ('BDX', 'Becton Dickinson', 'healthcare'),
            ('BEN', 'Franklin Templeton', 'financials'),
            ('BF-B', 'Brown-Forman', 'consumer-staples'),
            ('BIIB', 'Biogen', 'healthcare'),
            ('BK', 'Bank of New York Mellon', 'financials'),
            ('BKNG', 'Booking Holdings', 'consumer-discretionary'),
            ('BKR', 'Baker Hughes', 'energy'),
            ('BLK', 'BlackRock', 'financials'),
            ('BMY', 'Bristol-Myers Squibb', 'healthcare'),
            ('BR', 'Broadridge Financial', 'industrials'),
            ('BRK-B', 'Berkshire Hathaway', 'financials'),
            ('BRO', 'Brown & Brown', 'financials'),
            ('BSX', 'Boston Scientific', 'healthcare'),
            ('BWA', 'BorgWarner', 'consumer-discretionary'),
            ('BXP', 'BXP Inc', 'real-estate'),
            ('C', 'Citigroup', 'financials'),
            ('CAG', 'Conagra Brands', 'consumer-staples'),
            ('CAH', 'Cardinal Health', 'healthcare'),
            ('CARR', 'Carrier Global', 'industrials'),
            ('CAT', 'Caterpillar', 'industrials'),
            ('CB', 'Chubb', 'financials'),
            ('CBOE', 'Cboe Global Markets', 'financials'),
            ('CBRE', 'CBRE Group', 'real-estate'),
            ('CCI', 'Crown Castle', 'real-estate'),
            ('CCL', 'Carnival Corporation', 'consumer-discretionary'),
            ('CDAY', 'Ceridian HCM', 'industrials'),
            ('CDNS', 'Cadence Design Systems', 'tech'),
            ('CDW', 'CDW Corporation', 'tech'),
            ('CE', 'Celanese', 'materials'),
            ('CEG', 'Constellation Energy', 'utilities'),
            ('CF', 'CF Industries', 'materials'),
            ('CFG', 'Citizens Financial Group', 'financials'),
            ('CHD', 'Church & Dwight', 'consumer-staples'),
            ('CHRW', 'C.H. Robinson', 'industrials'),
            ('CHTR', 'Charter Communications', 'communication'),
            ('CI', 'Cigna Group', 'healthcare'),
            ('CINF', 'Cincinnati Financial', 'financials'),
            ('CL', 'Colgate-Palmolive', 'consumer-staples'),
            ('CLX', 'Clorox', 'consumer-staples'),
            ('CMA', 'Comerica', 'financials'),
            ('CMCSA', 'Comcast', 'communication'),
            ('CME', 'CME Group', 'financials'),
            ('CMG', 'Chipotle', 'consumer-discretionary'),
            ('CMI', 'Cummins', 'industrials'),
            ('CMS', 'CMS Energy', 'utilities'),
            ('CNC', 'Centene', 'healthcare'),
            ('CNP', 'CenterPoint Energy', 'utilities'),
            ('COF', 'Capital One Financial', 'financials'),
            ('COO', 'CooperCompanies', 'healthcare'),
            ('COP', 'ConocoPhillips', 'energy'),
            ('COST', 'Costco', 'consumer-staples'),
            ('CPB', 'Campbell Soup', 'consumer-staples'),
            ('CPRT', 'Copart', 'industrials'),
            ('CPT', 'Camden Property Trust', 'real-estate'),
            ('CRL', 'Charles River Laboratories', 'healthcare'),
            ('CRM', 'Salesforce', 'tech'),
            ('CSCO', 'Cisco Systems', 'tech'),
            ('CSGP', 'CoStar Group', 'real-estate'),
            ('CSX', 'CSX Corporation', 'industrials'),
            ('CTAS', 'Cintas', 'industrials'),
            ('CTLT', 'Catalent', 'healthcare'),
            ('CTRA', 'Coterra Energy', 'energy'),
            ('CTSH', 'Cognizant', 'tech'),
            ('CTVA', 'Corteva', 'materials'),
            ('CVS', 'CVS Health', 'healthcare'),
            ('CVX', 'Chevron', 'energy'),
            ('CZR', 'Caesars Entertainment', 'consumer-discretionary'),
            ('D', 'Dominion Energy', 'utilities'),
            ('DAL', 'Delta Air Lines', 'industrials'),
            ('DD', 'DuPont', 'materials'),
            ('DE', 'Deere & Company', 'industrials'),
            ('DFS', 'Discover Financial Services', 'financials'),
            ('DG', 'Dollar General', 'consumer-discretionary'),
            ('DGX', 'Quest Diagnostics', 'healthcare'),
            ('DHI', 'D.R. Horton', 'consumer-discretionary'),
            ('DHR', 'Danaher', 'healthcare'),
            ('DIS', 'Walt Disney', 'communication'),
            ('DISH', 'DISH Network', 'communication'),
            ('DLR', 'Digital Realty Trust', 'real-estate'),
            ('DLTR', 'Dollar Tree', 'consumer-discretionary'),
            ('DOV', 'Dover Corporation', 'industrials'),
            ('DOW', 'Dow Inc', 'materials'),
            ('DPZ', 'Domino\'s Pizza', 'consumer-discretionary'),
            ('DRI', 'Darden Restaurants', 'consumer-discretionary'),
            ('DTE', 'DTE Energy', 'utilities'),
            ('DUK', 'Duke Energy', 'utilities'),
            ('DVA', 'DaVita', 'healthcare'),
            ('DVN', 'Devon Energy', 'energy'),
            ('DXC', 'DXC Technology', 'tech'),
            ('DXCM', 'DexCom', 'healthcare'),
            ('EA', 'Electronic Arts', 'communication'),
            ('EBAY', 'eBay', 'consumer-discretionary'),
            ('ECL', 'Ecolab', 'materials'),
            ('ED', 'Consolidated Edison', 'utilities'),
            ('EFX', 'Equifax', 'industrials'),
            ('EIX', 'Edison International', 'utilities'),
            ('EL', 'Estee Lauder', 'consumer-staples'),
            ('EMN', 'Eastman Chemical', 'materials'),
            ('EMR', 'Emerson Electric', 'industrials'),
            ('ENPH', 'Enphase Energy', 'tech'),
            ('EOG', 'EOG Resources', 'energy'),
            ('EPAM', 'EPAM Systems', 'tech'),
            ('EQIX', 'Equinix', 'real-estate'),
            ('EQR', 'Equity Residential', 'real-estate'),
            ('EQT', 'EQT Corporation', 'energy'),
            ('ES', 'Eversource Energy', 'utilities'),
            ('ESS', 'Essex Property Trust', 'real-estate'),
            ('ETN', 'Eaton Corporation', 'industrials'),
            ('ETR', 'Entergy', 'utilities'),
            ('ETSY', 'Etsy', 'consumer-discretionary'),
            ('EVRG', 'Evergy', 'utilities'),
            ('EW', 'Edwards Lifesciences', 'healthcare'),
            ('EXC', 'Exelon', 'utilities'),
            ('EXPD', 'Expeditors International', 'industrials'),
            ('EXPE', 'Expedia Group', 'consumer-discretionary'),
            ('EXR', 'Extra Space Storage', 'real-estate'),
            ('F', 'Ford Motor', 'consumer-discretionary'),
            ('FANG', 'Diamondback Energy', 'energy'),
            ('FAST', 'Fastenal', 'industrials'),
            ('FBHS', 'Fortune Brands', 'industrials'),
            ('FCX', 'Freeport-McMoRan', 'materials'),
            ('FDS', 'FactSet Research', 'financials'),
            ('FDX', 'FedEx', 'industrials'),
            ('FE', 'FirstEnergy', 'utilities'),
            ('FFIV', 'F5 Networks', 'tech'),
            ('FIS', 'Fidelity National Info', 'financials'),
            ('FISV', 'Fiserv', 'financials'),
            ('FITB', 'Fifth Third Bancorp', 'financials'),
            ('FLT', 'Fleetcor Technologies', 'financials'),
            ('FMC', 'FMC Corporation', 'materials'),
            ('FOX', 'Fox Corporation', 'communication'),
            ('FRC', 'First Republic Bank', 'financials'),
            ('FRT', 'Federal Realty Trust', 'real-estate'),
            ('FTNT', 'Fortinet', 'tech'),
            ('FTV', 'Fortive', 'industrials'),
            ('GD', 'General Dynamics', 'industrials'),
            ('GE', 'General Electric', 'industrials'),
            ('GILD', 'Gilead Sciences', 'healthcare'),
            ('GIS', 'General Mills', 'consumer-staples'),
            ('GL', 'Globe Life', 'financials'),
            ('GLW', 'Corning', 'tech'),
            ('GM', 'General Motors', 'consumer-discretionary'),
            ('GNRC', 'Generac Holdings', 'industrials'),
            ('GOOG', 'Alphabet (Google)', 'communication'),
            ('GPC', 'Genuine Parts', 'consumer-discretionary'),
            ('GPN', 'Global Payments', 'financials'),
            ('GRMN', 'Garmin', 'tech'),
            ('GS', 'Goldman Sachs', 'financials'),
            ('GWW', 'W.W. Grainger', 'industrials'),
            ('HAL', 'Halliburton', 'energy'),
            ('HAS', 'Hasbro', 'consumer-discretionary'),
            ('HBAN', 'Huntington Bancshares', 'financials'),
            ('HCA', 'HCA Healthcare', 'healthcare'),
            ('HD', 'Home Depot', 'consumer-discretionary'),
            ('HOLX', 'Hologic', 'healthcare'),
            ('HON', 'Honeywell', 'industrials'),
            ('HPE', 'Hewlett Packard Enterprise', 'tech'),
            ('HPQ', 'HP Inc', 'tech'),
            ('HRL', 'Hormel Foods', 'consumer-staples'),
            ('HSIC', 'Henry Schein', 'healthcare'),
            ('HST', 'Host Hotels & Resorts', 'real-estate'),
            ('HSY', 'Hershey', 'consumer-staples'),
            ('HUM', 'Humana', 'healthcare'),
            ('HWM', 'Howmet Aerospace', 'industrials'),
            ('IBM', 'IBM', 'tech'),
            ('ICE', 'Intercontinental Exchange', 'financials'),
            ('IDXX', 'IDEXX Laboratories', 'healthcare'),
            ('IEX', 'IDEX Corporation', 'industrials'),
            ('IFF', 'International Flavors', 'materials'),
            ('ILMN', 'Illumina', 'healthcare'),
            ('INCY', 'Incyte', 'healthcare'),
            ('INTC', 'Intel', 'tech'),
            ('INTU', 'Intuit', 'tech'),
            ('INVH', 'Invitation Homes', 'real-estate'),
            ('IP', 'International Paper', 'materials'),
            ('IPG', 'Interpublic Group', 'communication'),
            ('IQV', 'IQVIA Holdings', 'healthcare'),
            ('IR', 'Ingersoll Rand', 'industrials'),
            ('IRM', 'Iron Mountain', 'real-estate'),
            ('ISRG', 'Intuitive Surgical', 'healthcare'),
            ('IT', 'Gartner', 'tech'),
            ('ITW', 'Illinois Tool Works', 'industrials'),
            ('IVZ', 'Invesco', 'financials'),
            ('J', 'Jacobs Solutions', 'industrials'),
            ('JBHT', 'J.B. Hunt Transport', 'industrials'),
            ('JCI', 'Johnson Controls', 'industrials'),
            ('JKHY', 'Jack Henry & Associates', 'financials'),
            ('JNJ', 'Johnson & Johnson', 'healthcare'),
            ('JNPR', 'Juniper Networks', 'tech'),
            ('JPM', 'JPMorgan Chase', 'financials'),
            ('K', 'Kellanova', 'consumer-staples'),
            ('KDP', 'Keurig Dr Pepper', 'consumer-staples'),
            ('KEY', 'KeyCorp', 'financials'),
            ('KEYS', 'Keysight Technologies', 'tech'),
            ('KHC', 'Kraft Heinz', 'consumer-staples'),
            ('KIM', 'Kimco Realty', 'real-estate'),
            ('KLAC', 'KLA Corporation', 'tech'),
            ('KMB', 'Kimberly-Clark', 'consumer-staples'),
            ('KMI', 'Kinder Morgan', 'energy'),
            ('KMX', 'CarMax', 'consumer-discretionary'),
            ('KO', 'Coca-Cola', 'consumer-staples'),
            ('KR', 'Kroger', 'consumer-staples'),
            ('L', 'Loews Corporation', 'financials'),
            ('LDOS', 'Leidos Holdings', 'industrials'),
            ('LEN', 'Lennar', 'consumer-discretionary'),
            ('LH', 'Labcorp Holdings', 'healthcare'),
            ('LHX', 'L3Harris Technologies', 'industrials'),
            ('LIN', 'Linde', 'materials'),
            ('LKQ', 'LKQ Corporation', 'consumer-discretionary'),
            ('LLY', 'Eli Lilly', 'healthcare'),
            ('LMT', 'Lockheed Martin', 'industrials'),
            ('LNC', 'Lincoln National', 'financials'),
            ('LNT', 'Alliant Energy', 'utilities'),
            ('LOW', 'Lowe\'s', 'consumer-discretionary'),
            ('LRCX', 'Lam Research', 'tech'),
            ('LULU', 'Lululemon Athletica', 'consumer-discretionary'),
            ('LUV', 'Southwest Airlines', 'industrials'),
            ('LVS', 'Las Vegas Sands', 'consumer-discretionary'),
            ('LW', 'Lamb Weston', 'consumer-staples'),
            ('LYB', 'LyondellBasell', 'materials'),
            ('LYV', 'Live Nation', 'communication'),
            ('MA', 'Mastercard', 'financials'),
            ('MAA', 'Mid-America Apartment', 'real-estate'),
            ('MAR', 'Marriott International', 'consumer-discretionary'),
            ('MAS', 'Masco', 'industrials'),
            ('MCD', 'McDonald\'s', 'consumer-discretionary'),
            ('MCHP', 'Microchip Technology', 'tech'),
            ('MCK', 'McKesson', 'healthcare'),
            ('MCO', 'Moody\'s', 'financials'),
            ('MDLZ', 'Mondelez International', 'consumer-staples'),
            ('MDT', 'Medtronic', 'healthcare'),
            ('MET', 'MetLife', 'financials'),
            ('META', 'Meta Platforms', 'communication'),
            ('MGM', 'MGM Resorts', 'consumer-discretionary'),
            ('MHK', 'Mohawk Industries', 'consumer-discretionary'),
            ('MKC', 'McCormick & Company', 'consumer-staples'),
            ('MKTX', 'MarketAxess', 'financials'),
            ('MLM', 'Martin Marietta', 'materials'),
            ('MMC', 'Marsh McLennan', 'financials'),
            ('MMM', '3M', 'industrials'),
            ('MNST', 'Monster Beverage', 'consumer-staples'),
            ('MO', 'Altria Group', 'consumer-staples'),
            ('MOH', 'Molina Healthcare', 'healthcare'),
            ('MOS', 'Mosaic Company', 'materials'),
            ('MPC', 'Marathon Petroleum', 'energy'),
            ('MPWR', 'Monolithic Power Systems', 'tech'),
            ('MRK', 'Merck', 'healthcare'),
            ('MRNA', 'Moderna', 'healthcare'),
            ('MRO', 'Marathon Oil', 'energy'),
            ('MS', 'Morgan Stanley', 'financials'),
            ('MSCI', 'MSCI Inc', 'financials'),
            ('MSFT', 'Microsoft', 'tech'),
            ('MSI', 'Motorola Solutions', 'tech'),
            ('MTB', 'M&T Bank', 'financials'),
            ('MTCH', 'Match Group', 'communication'),
            ('MTD', 'Mettler-Toledo', 'healthcare'),
            ('MU', 'Micron Technology', 'tech'),
            ('NCLH', 'Norwegian Cruise Line', 'consumer-discretionary'),
            ('NDAQ', 'Nasdaq Inc', 'financials'),
            ('NDSN', 'Nordson', 'industrials'),
            ('NEE', 'NextEra Energy', 'utilities'),
            ('NEM', 'Newmont', 'materials'),
            ('NFLX', 'Netflix', 'communication'),
            ('NI', 'NiSource', 'utilities'),
            ('NKE', 'Nike', 'consumer-discretionary'),
            ('NOC', 'Northrop Grumman', 'industrials'),
            ('NOW', 'ServiceNow', 'tech'),
            ('NRG', 'NRG Energy', 'utilities'),
            ('NSC', 'Norfolk Southern', 'industrials'),
            ('NTAP', 'NetApp', 'tech'),
            ('NTRS', 'Northern Trust', 'financials'),
            ('NUE', 'Nucor', 'materials'),
            ('NVDA', 'NVIDIA', 'tech'),
            ('NVR', 'NVR Inc', 'consumer-discretionary'),
            ('NWL', 'Newell Brands', 'consumer-discretionary'),
            ('NWS', 'News Corp', 'communication'),
            ('O', 'Realty Income', 'real-estate'),
            ('ODFL', 'Old Dominion Freight', 'industrials'),
            ('OGN', 'Organon', 'healthcare'),
            ('OKE', 'ONEOK', 'energy'),
            ('OMC', 'Omnicom Group', 'communication'),
            ('ON', 'ON Semiconductor', 'tech'),
            ('ORCL', 'Oracle', 'tech'),
            ('ORLY', 'O\'Reilly Automotive', 'consumer-discretionary'),
            ('OTIS', 'Otis Worldwide', 'industrials'),
            ('OXY', 'Occidental Petroleum', 'energy'),
            ('PARA', 'Paramount Global', 'communication'),
            ('PAYC', 'Paycom Software', 'industrials'),
            ('PAYX', 'Paychex', 'industrials'),
            ('PCAR', 'PACCAR', 'industrials'),
            ('PCG', 'PG&E', 'utilities'),
            ('PEAK', 'Healthpeak Properties', 'real-estate'),
            ('PEG', 'Public Service Enterprise', 'utilities'),
            ('PEP', 'PepsiCo', 'consumer-staples'),
            ('PFE', 'Pfizer', 'healthcare'),
            ('PFG', 'Principal Financial', 'financials'),
            ('PG', 'Procter & Gamble', 'consumer-staples'),
            ('PGR', 'Progressive', 'financials'),
            ('PH', 'Parker-Hannifin', 'industrials'),
            ('PHM', 'PulteGroup', 'consumer-discretionary'),
            ('PKG', 'Packaging Corp', 'materials'),
            ('PKI', 'PerkinElmer', 'healthcare'),
            ('PLD', 'Prologis', 'real-estate'),
            ('PM', 'Philip Morris', 'consumer-staples'),
            ('PNC', 'PNC Financial', 'financials'),
            ('PNR', 'Pentair', 'industrials'),
            ('PNW', 'Pinnacle West Capital', 'utilities'),
            ('POOL', 'Pool Corporation', 'consumer-discretionary'),
            ('PPG', 'PPG Industries', 'materials'),
            ('PPL', 'PPL Corporation', 'utilities'),
            ('PRU', 'Prudential Financial', 'financials'),
            ('PSA', 'Public Storage', 'real-estate'),
            ('PSX', 'Phillips 66', 'energy'),
            ('PTC', 'PTC Inc', 'tech'),
            ('PVH', 'PVH Corp', 'consumer-discretionary'),
            ('PWR', 'Quanta Services', 'industrials'),
            ('PXD', 'Pioneer Natural Resources', 'energy'),
            ('PYPL', 'PayPal', 'financials'),
            ('QCOM', 'Qualcomm', 'tech'),
            ('QRVO', 'Qorvo', 'tech'),
            ('RCL', 'Royal Caribbean', 'consumer-discretionary'),
            ('RE', 'Everest Group', 'financials'),
            ('REG', 'Regency Centers', 'real-estate'),
            ('REGN', 'Regeneron Pharmaceuticals', 'healthcare'),
            ('RF', 'Regions Financial', 'financials'),
            ('RHI', 'Robert Half', 'industrials'),
            ('RJF', 'Raymond James', 'financials'),
            ('RL', 'Ralph Lauren', 'consumer-discretionary'),
            ('RMD', 'ResMed', 'healthcare'),
            ('ROK', 'Rockwell Automation', 'industrials'),
            ('ROL', 'Rollins', 'consumer-discretionary'),
            ('ROP', 'Roper Technologies', 'industrials'),
            ('ROST', 'Ross Stores', 'consumer-discretionary'),
            ('RSG', 'Republic Services', 'industrials'),
            ('RTX', 'RTX Corporation', 'industrials'),
            ('SBAC', 'SBA Communications', 'real-estate'),
            ('SBNY', 'Signature Bank', 'financials'),
            ('SBUX', 'Starbucks', 'consumer-discretionary'),
            ('SCHW', 'Charles Schwab', 'financials'),
            ('SEE', 'Sealed Air', 'materials'),
            ('SHW', 'Sherwin-Williams', 'materials'),
            ('SIVB', 'SVB Financial Group', 'financials'),
            ('SJM', 'J.M. Smucker', 'consumer-staples'),
            ('SLB', 'Schlumberger', 'energy'),
            ('SNA', 'Snap-on', 'industrials'),
            ('SNPS', 'Synopsys', 'tech'),
            ('SO', 'Southern Company', 'utilities'),
            ('SPG', 'Simon Property Group', 'real-estate'),
            ('SPGI', 'S&P Global', 'financials'),
            ('SRE', 'Sempra', 'utilities'),
            ('STE', 'Steris', 'healthcare'),
            ('STT', 'State Street', 'financials'),
            ('STX', 'Seagate Technology', 'tech'),
            ('STZ', 'Constellation Brands', 'consumer-staples'),
            ('SWK', 'Stanley Black & Decker', 'industrials'),
            ('SWKS', 'Skyworks Solutions', 'tech'),
            ('SYF', 'Synchrony Financial', 'financials'),
            ('SYK', 'Stryker', 'healthcare'),
            ('SYY', 'Sysco', 'consumer-staples'),
            ('T', 'AT&T', 'communication'),
            ('TAP', 'Molson Coors', 'consumer-staples'),
            ('TDG', 'TransDigm Group', 'industrials'),
            ('TDY', 'Teledyne Technologies', 'industrials'),
            ('TECH', 'Bio-Techne', 'healthcare'),
            ('TEL', 'TE Connectivity', 'tech'),
            ('TER', 'Teradyne', 'tech'),
            ('TFC', 'Truist Financial', 'financials'),
            ('TFX', 'Teleflex', 'healthcare'),
            ('TGT', 'Target', 'consumer-discretionary'),
            ('TMO', 'Thermo Fisher Scientific', 'healthcare'),
            ('TMUS', 'T-Mobile US', 'communication'),
            ('TPR', 'Tapestry', 'consumer-discretionary'),
            ('TRGP', 'Targa Resources', 'energy'),
            ('TRMB', 'Trimble', 'tech'),
            ('TROW', 'T. Rowe Price', 'financials'),
            ('TRV', 'Travelers Companies', 'financials'),
            ('TSCO', 'Tractor Supply', 'consumer-discretionary'),
            ('TSLA', 'Tesla', 'consumer-discretionary'),
            ('TSN', 'Tyson Foods', 'consumer-staples'),
            ('TT', 'Trane Technologies', 'industrials'),
            ('TTWO', 'Take-Two Interactive', 'communication'),
            ('TXN', 'Texas Instruments', 'tech'),
            ('TXT', 'Textron', 'industrials'),
            ('TYL', 'Tyler Technologies', 'tech'),
            ('UAL', 'United Airlines', 'industrials'),
            ('UDR', 'UDR Inc', 'real-estate'),
            ('UHS', 'Universal Health Services', 'healthcare'),
            ('ULTA', 'Ulta Beauty', 'consumer-discretionary'),
            ('UNH', 'UnitedHealth Group', 'healthcare'),
            ('UNP', 'Union Pacific', 'industrials'),
            ('UPS', 'United Parcel Service', 'industrials'),
            ('URI', 'United Rentals', 'industrials'),
            ('USB', 'U.S. Bancorp', 'financials'),
            ('V', 'Visa', 'financials'),
            ('VFC', 'VF Corporation', 'consumer-discretionary'),
            ('VICI', 'VICI Properties', 'real-estate'),
            ('VLO', 'Valero Energy', 'energy'),
            ('VMC', 'Vulcan Materials', 'materials'),
            ('VRSK', 'Verisk Analytics', 'industrials'),
            ('VRSN', 'VeriSign', 'tech'),
            ('VRTX', 'Vertex Pharmaceuticals', 'healthcare'),
            ('VTR', 'Ventas', 'real-estate'),
            ('VTRS', 'Viatris', 'healthcare'),
            ('VZ', 'Verizon', 'communication'),
            ('WAB', 'Westinghouse Air Brake', 'industrials'),
            ('WAT', 'Waters Corporation', 'healthcare'),
            ('WBA', 'Walgreens Boots Alliance', 'consumer-staples'),
            ('WBD', 'Warner Bros Discovery', 'communication'),
            ('WDC', 'Western Digital', 'tech'),
            ('WEC', 'WEC Energy Group', 'utilities'),
            ('WELL', 'Welltower', 'real-estate'),
            ('WFC', 'Wells Fargo', 'financials'),
            ('WHR', 'Whirlpool', 'consumer-discretionary'),
            ('WM', 'Waste Management', 'industrials'),
            ('WMB', 'Williams Companies', 'energy'),
            ('WMT', 'Walmart', 'consumer-discretionary'),
            ('WRB', 'W.R. Berkley', 'financials'),
            ('WRK', 'WestRock', 'materials'),
            ('WST', 'West Pharmaceutical', 'healthcare'),
            ('WTW', 'Willis Towers Watson', 'financials'),
            ('WY', 'Weyerhaeuser', 'real-estate'),
            ('WYNN', 'Wynn Resorts', 'consumer-discretionary'),
            ('XEL', 'Xcel Energy', 'utilities'),
            ('XOM', 'ExxonMobil', 'energy'),
            ('XRAY', 'Dentsply Sirona', 'healthcare'),
            ('XYL', 'Xylem', 'industrials'),
            ('YUM', 'Yum! Brands', 'consumer-discretionary'),
            ('ZBH', 'Zimmer Biomet', 'healthcare'),
            ('ZBRA', 'Zebra Technologies', 'tech'),
            ('ZION', 'Zions Bancorporation', 'financials'),
            ('ZTS', 'Zoetis', 'healthcare'),
        ]

        created = 0
        skipped = 0
        for ticker, name, ind_slug in companies:
            slug = name.lower().replace(' ', '-').replace('&', 'and').replace('.', '').replace("'", '').replace('(', '').replace(')', '').replace(',', '').replace('/', '-')
            # Skip if already exists
            if Company.objects.filter(stock_ticker=ticker).exists() or Company.objects.filter(slug=slug).exists():
                skipped += 1
                continue

            Company.objects.create(
                name=name,
                slug=slug,
                stock_ticker=ticker,
                industry=industry_objs.get(ind_slug),
                risk_level='insufficient',
                summary_line='',
                pattern_summary='',
            )
            created += 1

        self.stdout.write(self.style.SUCCESS(
            f'S&P 500 seeding complete: {created} created, {skipped} already existed'
        ))
