# Generated by Django 6.0.5 on 2026-05-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(unique=True)),
                ("legal_name", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("osha_establishment_ids", models.JSONField(blank=True, default=list)),
                ("epa_facility_ids", models.JSONField(blank=True, default=list)),
                ("sec_cik", models.CharField(blank=True, max_length=20)),
                ("fec_committee_ids", models.JSONField(blank=True, default=list)),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=300)),
                ("stock_ticker", models.CharField(blank=True, max_length=10)),
                ("website", models.URLField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("elevated", "Elevated Concern"),
                            ("mixed", "Mixed Record"),
                            ("limited", "Limited Issues"),
                            ("insufficient", "Insufficient Data"),
                        ],
                        default="insufficient",
                        max_length=20,
                    ),
                ),
                ("summary_line", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "industries",
            },
        ),
        migrations.CreateModel(
            name="AccountabilityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("workplace", "Workplace Safety"),
                            ("environmental", "Environmental"),
                            ("governance", "Governance"),
                            ("labor", "Labor Relations"),
                            ("political", "Political Spending"),
                            ("consumer", "Consumer Protection"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("serious", "Serious"),
                            ("moderate", "Moderate"),
                            ("minor", "Minor"),
                            ("informational", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_agency", models.CharField(max_length=200)),
                ("source_url", models.URLField(blank=True)),
                ("source_document", models.CharField(blank=True, max_length=300)),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("facility_location", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="warden.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=200)),
                ("source_agency", models.CharField(max_length=200)),
                ("source_url", models.URLField(blank=True)),
                ("last_checked", models.DateField()),
                ("coverage_start", models.DateField(blank=True, null=True)),
                ("coverage_end", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="warden.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warden.industry",
            ),
        ),
        migrations.CreateModel(
            name="SnapshotStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=100)),
                ("context", models.CharField(blank=True, max_length=300)),
                ("source_url", models.URLField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_stats",
                        to="warden.company",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Subsidiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidiaries",
                        to="warden.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "subsidiaries",
            },
        ),
    ]
