# Generated by Django 6.0.5 on 2026-05-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warden", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pattern_summary",
            field=models.TextField(blank=True),
        ),
    ]
